name = "bare_svd"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Olivier Henley"]
maintainers = ["Olivier Henley <olivier.henley@gmail.com>"]
maintainers-logins = ["ohenley"]

[configuration.variables]
family = { type = "Enum", values = ["stm32", "nordic"], default = "stm32" }
soc_remainder = { type = "Enum", values = ["xx", "x29x"], default = "xx" }

[[depends-on]]
bare_types = "0.1.0-dev"
bare_core = "0.1.0-dev"